allowBuilds:
  '@nestjs/core': false
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  prisma: false
  unrs-resolver: false

overrides:
  body-parser: 2.3.0
  brace-expansion@1.1.14: 1.1.18
  brace-expansion@2.1.0: 2.1.4
  brace-expansion@5.0.6: 5.0.9
  fast-uri@3.1.2: 3.1.5
  form-data@4.0.5: 4.0.6
  js-yaml@3.14.2: 3.15.1
  js-yaml@4.1.1: 4.3.1
  multer: 2.2.0

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - arm64
    - x64
  libc:
    - glibc
