export type SummitCatalogEntry = {
  id: string;
  name: string;
  aliases?: string[];
  altitude: number;
  massif: string;
  difficulty: string;
  type: string;
  coordinates: readonly [number, number];
  imageUrl?: string;
  imageCredit?: string;
  sourceUrl?: string;
};

export const SUMMIT_CATALOG: SummitCatalogEntry[] = [
  {
    id: 'mont-veyrier',
    name: 'Mont Veyrier',
    altitude: 1291,
    massif: 'Annecy',
    difficulty: 'Difficile',
    type: 'Crête',
    coordinates: [6.18, 45.903],
    imageUrl: '/summits/mont-veyrier.webp',
    imageCredit: 'Photo : Yann Forget',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lac_veyrier2.jpg',
  },
  {
    id: 'mont-baron',
    name: 'Mont Baron',
    altitude: 1299,
    massif: 'Annecy',
    difficulty: 'Difficile',
    type: 'Crête',
    coordinates: [6.181, 45.914],
    imageUrl: '/summits/mont-baron.webp',
    imageCredit: 'Photo : Myrabella',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Chemin_mont_Veyrier_mont_Baron.jpg',
  },
  {
    id: 'semnoz',
    name: 'Semnoz',
    altitude: 1699,
    massif: 'Bauges',
    difficulty: 'Modérée',
    type: 'Sommet',
    coordinates: [6.104, 45.797],
    imageUrl: '/summits/semnoz.webp',
    imageCredit: 'Photo : Didier',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Semnoz_vu_de_menthon.jpg',
  },
  {
    id: 'cret-de-chatillon',
    name: 'Crêt de Châtillon',
    altitude: 1699,
    massif: 'Bauges',
    difficulty: 'Modérée',
    type: 'Belvédère',
    coordinates: [6.103, 45.797],
    imageUrl: '/summits/cret-de-chatillon.webp',
    imageCredit: 'Photo : Guilhem Vellut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Cr%C3%AAt_de_Ch%C3%A2tillon_@_Semnoz_(50933120682).jpg',
  },
  {
    id: 'roc-de-chere',
    name: 'Roc de Chère',
    altitude: 651,
    massif: 'Annecy',
    difficulty: 'Facile',
    type: 'Belvédère',
    coordinates: [6.212, 45.844],
    imageUrl: '/summits/roc-de-chere.webp',
    imageCredit: 'Photo : Florian Pépellin',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Roc_de_Ch%C3%A8re_et_lac_d%27Annecy_(printemps_2023).JPG',
  },
  {
    id: 'parmelan',
    name: 'Parmelan',
    altitude: 1856,
    massif: 'Bornes',
    difficulty: 'Difficile',
    type: 'Sommet',
    coordinates: [6.235, 45.963],
    imageUrl: '/summits/parmelan.webp',
    imageCredit: 'Photo : Guilhem Vellut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:T%C3%AAte_du_Parmelan_@_Villaz_(51105086198).jpg',
  },
  {
    id: 'la-tournette',
    name: 'La Tournette',
    altitude: 2351,
    massif: 'Bornes',
    difficulty: 'Expert',
    type: 'Sommet',
    coordinates: [6.287, 45.827],
    imageUrl: '/summits/la-tournette.webp',
    imageCredit: 'Photo : Guilhem Vellut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:La_Tournette_@_Lake_Annecy_@_Saint-Jorioz_(50488455392).jpg',
  },
  {
    id: 'pointe-de-talamarche',
    name: 'Pointe de Talamarche',
    aliases: ['Talamarche'],
    altitude: 1852,
    massif: 'Bornes',
    difficulty: 'Difficile',
    type: 'Sommet',
    coordinates: [6.25734, 45.85981],
    imageUrl: '/summits/pointe-de-talamarche.webp',
    imageCredit: 'Photo : Guilhem Vellut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Pointe_de_Talamarche_@_Hike_to_Lanfonnet_%26_Pointe_de_Talamarche_(15353800805).jpg',
  },
  {
    id: 'mont-lachat-de-thones',
    name: 'Mont Lachat de Thônes',
    altitude: 2023,
    massif: 'Bornes',
    difficulty: 'Difficile',
    type: 'Sommet',
    coordinates: [6.446, 45.958],
    imageUrl: '/summits/mont-lachat-de-thones.webp',
    imageCredit: 'Photo : Guilhem Vellut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Mont_Lachat_(51015342921).jpg',
  },
  {
    id: 'aiguille-verte-bargy',
    name: 'Aiguille Verte du Bargy',
    aliases: ['Aiguille Verte'],
    altitude: 2045,
    massif: 'Bargy',
    difficulty: 'Difficile',
    type: 'Sommet',
    coordinates: [6.432661, 45.982277],
    imageUrl: '/summits/aiguille-verte-bargy.webp',
    imageCredit: 'Photo : Rémih',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Aiguille_Verte_@_Col_Sous_le_Buclon.jpg',
  },
  {
    id: 'le-buclon',
    name: 'Le Buclon',
    altitude: 2072,
    massif: 'Bargy',
    difficulty: 'Difficile',
    type: 'Sommet',
    coordinates: [6.445161, 45.98641],
    imageUrl: '/summits/le-buclon.webp',
    imageCredit: 'Photo : Guilhem Vellut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Le_Buclon_@_Le_Grand-Bornand_(51045092073).jpg',
  },
  {
    id: 'lanfonnet',
    name: 'Lanfonnet',
    altitude: 1768,
    massif: 'Bornes',
    difficulty: 'Difficile',
    type: 'Arête',
    coordinates: [6.259, 45.842],
    imageUrl: '/summits/lanfonnet.webp',
    imageCredit: 'Photo : Guilhem Vellut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Dents_de_Lanfon_%26_Lanfonnet_@_Saint-Jorioz_(50470892721).jpg',
  },
  {
    id: 'dent-de-lanfon',
    name: 'Dent de Lanfon',
    altitude: 1824,
    massif: 'Bornes',
    difficulty: 'Expert',
    type: 'Arête',
    coordinates: [6.251, 45.849],
    imageUrl: '/summits/dent-de-lanfon.webp',
    imageCredit: 'Photo : Thomas Basset',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Dents_de_Lanfon_falaise_Nord.jpg',
  },
  {
    id: 'sulens',
    name: 'Sulens',
    altitude: 1839,
    massif: 'Aravis',
    difficulty: 'Modérée',
    type: 'Sommet',
    coordinates: [6.362, 45.85],
    imageUrl: '/summits/sulens.webp',
    imageCredit: 'Photo : Guilhem Vellut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Montagne_de_Sulens_(51377181065).jpg',
  },
  {
    id: 'mont-charvin',
    name: 'Mont Charvin',
    altitude: 2409,
    massif: 'Aravis',
    difficulty: 'Expert',
    type: 'Sommet',
    coordinates: [6.41, 45.809],
    imageUrl: '/summits/mont-charvin.webp',
    imageCredit: 'Photo : Nicolas Vigier',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Le_Mont_Charvin.jpg',
  },
  {
    id: 'pointe-percee',
    name: 'Pointe Percée',
    altitude: 2750,
    massif: 'Aravis',
    difficulty: 'Expert',
    type: 'Sommet',
    coordinates: [6.555, 45.955],
    imageUrl: '/summits/pointe-percee.webp',
    imageCredit: 'Photo : Guilhem Vellut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Pointe_Perc%C3%A9e_@_Aravis_@_Belv%C3%A9d%C3%A8re_@_Semnoz_(50936218957).jpg',
  },
  {
    id: 'tete-pelouse',
    name: 'Tête Pelouse',
    altitude: 2537,
    massif: 'Aravis',
    difficulty: 'Expert',
    type: 'Sommet',
    coordinates: [6.481, 45.978],
    imageUrl: '/summits/tete-pelouse.webp',
    imageCredit: 'Photo : Guilhem Vellut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:T%C3%AAte_Pelouse_@_La_Clusaz_(51199115282).jpg',
  },
  {
    id: 'la-sambuy',
    name: 'La Sambuy',
    altitude: 2198,
    massif: 'Bauges',
    difficulty: 'Difficile',
    type: 'Sommet',
    coordinates: [6.284, 45.692],
    imageUrl: '/summits/la-sambuy.webp',
    imageCredit: 'Photo : Rémih',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Pointe_de_la_Sambuy.jpg',
  },
  {
    id: 'montagne-de-sous-dine',
    name: 'Montagne de Sous-Dine',
    altitude: 2004,
    massif: 'Bornes',
    difficulty: 'Difficile',
    type: 'Sommet',
    coordinates: [6.319, 46.024],
    imageUrl: '/summits/montagne-de-sous-dine.webp',
    imageCredit: 'Photo : Guilhem Vellut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Montagne_de_Sous-Dine_@_Filli%C3%A8re_(51019671756).jpg',
  },
  {
    id: 'le-mole',
    name: 'Le Môle',
    altitude: 1863,
    massif: 'Chablais',
    difficulty: 'Modérée',
    type: 'Sommet',
    coordinates: [6.457, 46.106],
    imageUrl: '/summits/le-mole.webp',
    imageCredit: 'Photo : Guilhem Vellut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Le_M%C3%B4le_@_Bonneville_(50995766398).jpg',
  },
  {
    id: 'aiguille-du-midi',
    name: 'Aiguille du Midi',
    altitude: 3842,
    massif: 'Mont-Blanc',
    difficulty: 'Expert',
    type: 'Sommet',
    coordinates: [6.887, 45.878],
    imageUrl: '/summits/aiguille-du-midi.webp',
    imageCredit: 'Photo : Tangopaso',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Aiguille_du_Midi_from_Chamonix.jpg',
  },
  {
    id: 'mont-blanc',
    name: 'Mont Blanc',
    altitude: 4808,
    massif: 'Mont-Blanc',
    difficulty: 'Expert',
    type: 'Sommet',
    coordinates: [6.865, 45.833],
    imageUrl: '/summits/mont-blanc.webp',
    imageCredit: 'Photo : Hseugut',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Mont_Blanc_Aiguille.jpg',
  },
  {
    id: 'le-brevent',
    name: 'Le Brévent',
    altitude: 2525,
    massif: 'Aiguilles Rouges',
    difficulty: 'Difficile',
    type: 'Belvédère',
    coordinates: [6.837, 45.934],
    imageUrl: '/summits/le-brevent.webp',
    imageCredit: 'Photo : Franck Langlois',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Br%C3%A9vent_Depuis_Chamonix_19082008.jpg',
  },
  {
    id: 'aiguille-verte',
    name: 'Aiguille Verte du Mont-Blanc',
    aliases: ['Aiguille Verte'],
    altitude: 4122,
    massif: 'Mont-Blanc',
    difficulty: 'Expert',
    type: 'Sommet',
    coordinates: [6.969, 45.934],
    imageUrl: '/summits/aiguille-verte.webp',
    imageCredit: 'Photo : Jacek Rużyczka',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Aiguille_Verte_depuis_l%27Aiguille_du_Midi.jpg',
  },
];
